# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pins_constraints.xdc

# Block Designs: bd/AXI_Integration/AXI_Integration.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_Integration || ORIG_REF_NAME==AXI_Integration} -quiet] -quiet

# IP: bd/AXI_Integration/ip/AXI_Integration_processing_system7_0_0/AXI_Integration_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_Integration_processing_system7_0_0 || ORIG_REF_NAME==AXI_Integration_processing_system7_0_0} -quiet] -quiet

# IP: bd/AXI_Integration/ip/AXI_Integration_myip_0_0/AXI_Integration_myip_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_Integration_myip_0_0 || ORIG_REF_NAME==AXI_Integration_myip_0_0} -quiet] -quiet

# IP: bd/AXI_Integration/ip/AXI_Integration_ps7_0_axi_periph_1/AXI_Integration_ps7_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_Integration_ps7_0_axi_periph_1 || ORIG_REF_NAME==AXI_Integration_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/AXI_Integration/ip/AXI_Integration_rst_ps7_0_50M_1/AXI_Integration_rst_ps7_0_50M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_Integration_rst_ps7_0_50M_1 || ORIG_REF_NAME==AXI_Integration_rst_ps7_0_50M_1} -quiet] -quiet

# IP: bd/AXI_Integration/ip/AXI_Integration_auto_pc_0/AXI_Integration_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_Integration_auto_pc_0 || ORIG_REF_NAME==AXI_Integration_auto_pc_0} -quiet] -quiet

# XDC: c:/LocalWorkspace/EE277workspace/Lab2_2021v/Lab2_AXILiteImplement2021/Lab2_AXILiteImplement2021.gen/sources_1/bd/AXI_Integration/AXI_Integration_ooc.xdc
