# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Pranav/LocalWorkspace/EE277/EE277_Final_Project/EE277_FinalProject_Dec16_2024/Impl_1/vivado/hw/hw.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
# IP: The module: 'design_1_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Pranav/LocalWorkspace/EE277/EE277_Final_Project/EE277_FinalProject_Dec16_2024/Impl_1/vivado/hw/hw.gen/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Pranav/LocalWorkspace/EE277/EE277_Final_Project/EE277_FinalProject_Dec16_2024/Impl_1/vivado/hw/hw.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
# IP: The module: 'design_1_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Pranav/LocalWorkspace/EE277/EE277_Final_Project/EE277_FinalProject_Dec16_2024/Impl_1/vivado/hw/hw.gen/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
