# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/LocalWorkspace/EE277workspace/Lab2_2021v/Lab2_AXILiteImplement2021/Lab2_AXILiteImplement2021.srcs/sources_1/bd/AXI_Integration/ip/AXI_Integration_auto_pc_0/AXI_Integration_auto_pc_0.xci
# IP: The module: 'AXI_Integration_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/LocalWorkspace/EE277workspace/Lab2_2021v/Lab2_AXILiteImplement2021/Lab2_AXILiteImplement2021.gen/sources_1/bd/AXI_Integration/ip/AXI_Integration_auto_pc_0/AXI_Integration_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_Integration_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/LocalWorkspace/EE277workspace/Lab2_2021v/Lab2_AXILiteImplement2021/Lab2_AXILiteImplement2021.srcs/sources_1/bd/AXI_Integration/ip/AXI_Integration_auto_pc_0/AXI_Integration_auto_pc_0.xci
# IP: The module: 'AXI_Integration_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/LocalWorkspace/EE277workspace/Lab2_2021v/Lab2_AXILiteImplement2021/Lab2_AXILiteImplement2021.gen/sources_1/bd/AXI_Integration/ip/AXI_Integration_auto_pc_0/AXI_Integration_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_Integration_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
