# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/LocalWorkspace/EE277workspace/FinalProject/hw_pynq/hw.srcs/sources_1/bd/design_1/ip/design_1_s01_regslice_0/design_1_s01_regslice_0.xci
# IP: The module: 'design_1_s01_regslice_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/LocalWorkspace/EE277workspace/FinalProject/hw_pynq/hw.gen/sources_1/bd/design_1/ip/design_1_s01_regslice_0/design_1_s01_regslice_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_s01_regslice_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/LocalWorkspace/EE277workspace/FinalProject/hw_pynq/hw.gen/sources_1/bd/design_1/ip/design_1_s01_regslice_0/design_1_s01_regslice_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_s01_regslice_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/LocalWorkspace/EE277workspace/FinalProject/hw_pynq/hw.srcs/sources_1/bd/design_1/ip/design_1_s01_regslice_0/design_1_s01_regslice_0.xci
# IP: The module: 'design_1_s01_regslice_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/LocalWorkspace/EE277workspace/FinalProject/hw_pynq/hw.gen/sources_1/bd/design_1/ip/design_1_s01_regslice_0/design_1_s01_regslice_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_s01_regslice_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/LocalWorkspace/EE277workspace/FinalProject/hw_pynq/hw.gen/sources_1/bd/design_1/ip/design_1_s01_regslice_0/design_1_s01_regslice_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_s01_regslice_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
